[tool.poetry]
name = "funnel-cake"
version = "0.1.0"
description = ""
authors = ["Ian Graham <irgraham1@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
numpy = "1.20"
scipy = "1.4.1"
matplotlib = "3.1.3"
pandas = "^1.2"
pysbatch = "0.1.6"

[virtualenvs]
create = true
in-project = true